GET http://localhost:8080/api/teachers/Salam

###
POST http://localhost:8080/api/teachers
Content-Type: application/json

{
  "username": "Salam",
  "role": "TEACHER"
}

###
GET http://localhost:8080/api/teachers

###
DELETE http://localhost:8080/api/teachers/3