GET http://localhost:8085/api/teachers/merve

###
POST http://localhost:8085/api/teachers
Content-Type: application/json

{
  "username": "marwa",
  "role": "TEACHER"
}

###
GET http://localhost:8085/api/teachers

###
DELETE http://localhost:8085/api/teachers/3